Project: STP>Solar-Terrestrial Physics
Source_name: IMAP>Interstellar Mapping and Acceleration Probe
Discipline: Solar Physics>Heliospheric Physics
# TODO: CDF docs say this value should be IMAP
Mission_group: IMAP>Interstellar Mapping and Acceleration Probe
PI_name: Dr. David J. McComas
PI_affiliation: Princeton Plasma Physics Laboratory, 100 Stellarator Road, Princeton, NJ 08540
File_naming_convention: source_descriptor_datatype_yyyyMMdd_vNNN
