# ------- Default attributes section -------
default_attrs: &default
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FORMAT: I12
  UNITS: " "
  VAR_TYPE: data
  SCALE_TYPE: linear

default_uint8_attrs: &default_uint8
  <<: *default
  FILLVAL: 255
  FORMAT: I3
  VALIDMIN: 0
  VALIDMAX: 255
  dtype: uint8

default_uint16_attrs: &default_uint16
  <<: *default
  FILLVAL: 65535
  FORMAT: I5
  VALIDMIN: 0
  VALIDMAX: 65535
  dtype: uint16

default_uint32_attrs: &default_uint32
  <<: *default
  FILLVAL: 4294967295
  FORMAT: I10
  VALIDMIN: 0
  VALIDMAX: 4294967295
  dtype: uint32

default_uint64_attrs: &default_uint64
  <<: *default
  FILLVAL: 18446744073709551615
  FORMAT: I20
  VALIDMIN: 0
  VALIDMAX: 18446744073709551615
  dtype: uint64

default_int32_attrs: &default_int32
  <<: *default
  FILLVAL: -2147483648
  FORMAT: I10
  VALIDMIN: -2147483648
  VALIDMAX: 2147483647
  dtype: int32

default_float32_attrs: &default_float32
  <<: *default
  FILLVAL: .NAN
  FORMAT: F10.2
  VALIDMIN: -3.4028235e+38
  VALIDMAX: 3.4028235e+38
  dtype: float32

default_epoch: &default_epoch
  CATDESC: Time, number of nanoseconds since J2000 with leap seconds included
  FIELDNAM: epoch
  LABLAXIS: epoch
  FILLVAL: -9223372036854775808
  FORMAT: " " # Supposedly not required, fails in xarray_to_cdf
  VALIDMIN: -9223372036854775808
  VALIDMAX: 9223372036854775807
  UNITS: ns
  VAR_TYPE: support_data
  SCALETYP: linear
  MONOTON: INCREASE
  TIME_BASE: J2000
  TIME_SCALE: Terrestrial Time
  REFERENCE_POSITION: Rotating Earth Geoid
  dtype: int64

default_ccsds_met: &hi_ccsds_met
  <<: *default_uint32
  CATDESC: CCSDS mission elapsed time (MET). 32-bit integer value that represents the MET in seconds.
  FIELDNAM: Mission Elapsed Time(MET)
  LABLAXIS: CCSDS MET
  UNITS: sec
  VAR_TYPE: support_data

hi_esa_stepping_num: &hi_esa_stepping_num
  <<: *default_uint8
  CATDESC: Zero based index indicates which row of onboard stepping table was used
  FIELDNAM: ESA stepping number
  FILLVAL: 255
  FORMAT: I2
  LABLAXIS: Stepping Num
  VALIDMIN: 0
  VALIDMAX: 16
  VAR_NOTES: >
    ESA (electrostatic analyzer) stepping number is 4-bit integer value that indicates
    which row of the onboard stepping table was used to set voltages of the inner and
    outer ESA surfaces.

# ======= L1A DE Section =======
hi_de_ccsds_met:
  <<: *hi_ccsds_met

hi_de_de_tag:
  <<: *default_uint16
  CATDESC: Ticks (nominally 2 ms) since last meta-event
  FIELDNAM: Direct Event Time Tag
  LABLAXIS: DE Time Tag

hi_de_epoch:
  <<: *default_epoch
  CATDESC: Direct Event time, number of nanoseconds since J2000 with leap seconds included

hi_de_esa_stepping_num:
  <<: *hi_esa_stepping_num

hi_de_event_met:
  <<: *default_uint64
  CATDESC: Mission Elapsed Time (MET) of Direct Event
  DISPLAY_TYPE: no_plot
  FIELDNAM: Time since (TODO - what is the def of MET?)
  LABLAXIS: DE MET
  UNITS: ns
  VAR_TYPE: support_data
  SCALE_TYP: linear

hi_de_meta_event_met:
  <<: *default_uint64
  CATDESC: Mission elapsed time (MET) of last meta-event
  DISPLAY_TYPE: no_plot
  FIELDNAM: Meta-event Mission Elapsed Time
  LABLAXIS: Meta MET
  UNITS: ns
  VALIDMIN: 0
  VALIDMAX: 4294967295
  VAR_TYPE: support_data
  SCALE_TYP: linear
  dtype: uint64

hi_de_trigger_id:
  <<: *default_uint8
  CATDESC: Trigger ID of the detector that was hit first
  FIELDNAM: Trigger ID
  FILLVAL: 0
  FORMAT: I1
  LABLAXIS: ID
  VALIDMIN: 1
  VALIDMAX: 3
  VAR_NOTES: >
    The trigger ID is 2-bits. It represents which detector was
    hit first. It can be 1, 2, 3 for detector A, B, C respectively.

default_tof: &default_tof
  <<: *default_uint16
  FORMAT: I4
  UNITS: ticks
  VALIDMAX: 1023
  VAR_NOTES: >
    Time of flight is 10-bit integer value that represents the time of flight of
    the direct event. 1023 and 511 are values used to indicate no event was registered.

hi_de_tof_1:
  <<: *default_tof
  CATDESC: Time of flight of direct event, 1023 or 511 indicates no event registered
  FIELDNAM: Time of Flight (TOF) 1
  LABLAXIS: TOF1

hi_de_tof_2:
  <<: *default_tof
  CATDESC: Time of flight of direct event, 1023 or 511 indicates no event registered
  FIELDNAM: Time of Flight (TOF) 2
  LABLAXIS: TOF2

hi_de_tof_3:
  <<: *default_tof
  CATDESC: Time of flight of direct event, 1023 indicates no event registered
  FIELDNAM: Time of Flight (TOF) 3
  LABLAXIS: TOF3
  VAR_NOTES: >
    Time of flight is 10-bit integer value that represents the time of flight of
    the direct event. 1023 is the value used to indicate no event was registered.

# ======= L1A HIST Section =======
hi_hist_epoch:
  <<: *default_epoch

hi_hist_angle:
  SCALE_TYPE: linear
  CATDESC: Angle bin centers for histogram data.
  FIELDNAM: ANGLE
  FILLVAL: 65535
  VALIDMIN: 0
  VALIDMAX: 360
  FORMAT: I3
  UNITS: deg
  LABLAXIS: ANGLE
  VAR_TYPE: support_data
  dtype: uint16

hi_hist_ccsds_met:
  <<: *hi_ccsds_met

hi_hist_esa_stepping_num:
  <<: *hi_esa_stepping_num

hi_hist_counters:
  <<: *default_uint16
  CATDESC: Angular histogram of {counter_name} type events
  FIELDNAM: "{counter_name} histogram"
  VALIDMAX: 4095
  DEPEND_1: angle
  FORMAT: I4
  LABLAXIS: "{counter_name}"

# ======= L1B DE Section =======
hi_de_coincidence_type:
  <<: *default_uint8
  CATDESC: Bitmap of detectors hit for Direct Event
  FIELDNAM: Coincidence Type
  FILLVAL: 0
  FORMAT: I2
  LABLAXIS: Type
  VALIDMIN: 0
  VALIDMAX: 15
  VAR_NOTES: >
    A 4-bit quantity, representable as a hexadecimal digit,
    made up of the ORed quantities: (A hit? 8:0) | (B hit? 4:0)
    | (C1 hit? 2:0) | (C2 hit? 1 : 0)

default_esa_step: &default_esa_step
  CATDESC: Zero based energy step index
  FIELDNAM: ESA energy step
  FILLVAL: 255
  FORMAT: I2
  VALIDMIN: 0
  VALIDMAX: 12

hi_de_esa_step:
  <<: *default_uint8
  <<: *default_esa_step
  LABLAXIS: Energy Step

default_delta_t: &default_delta_t
  <<: *default_int32
  FORMAT: I3
  LABLAXIS: delta T
  UNITS: ns
  VALIDMIN: -512
  VALIDMAX: 512

hi_de_delta_t_ab:
  <<: *default_delta_t
  CATDESC: Time difference between detector A and B events (t_B - t_A)
  FIELDNAM: Delta T, event A to B

hi_de_delta_t_ac1:
  <<: *default_delta_t
  CATDESC: Time difference between detector A and C1 events (t_C1 - t_A)
  FIELDNAM: Delta T, event A to C1

hi_de_delta_t_bc1:
  <<: *default_delta_t
  CATDESC: Time difference between detector B and C1 events (t_C1 - t_B)
  FIELDNAM: Delta T, event B to C1

hi_de_delta_t_c1c2:
  <<: *default_delta_t
  CATDESC: Time difference between detector C1 and C2 events (t_C2 - t_C1)
  FIELDNAM: Delta T, event C1 to C2

hi_de_spin_phase:
  <<: *default_float32
  CATDESC: Floating point spin phase
  FIELDNAM: Spin Phase
  FORMAT: F4.3
  LABLAXIS: Spin Phase
  VALIDMIN: 0
  VALIDMAX: 1

hi_de_hae_latitude:
  <<: *default_float32
  CATDESC: Look direction HAE latitude
  FIELDNAM: Ecliptic Lattitude
  FORMAT: F5.2
  LABLAXIS: Lat
  VALIDMIN: -180
  VALIDMAX: 180
  UNITS: deg

hi_de_hae_longitude:
  <<: *default_float32
  CATDESC: Look direction HAE longitude
  FIELDNAM: Ecliptic Longitude
  FORMAT: F5.2
  LABLAXIS: Lon
  VALIDMIN: 0
  VALIDMAX: 360
  UNITS: deg

hi_de_quality_flag:
  <<: *default_uint16
  CATDESC: Direct event bitwise quality flag
  FIELDNAM: DE quality flag
  FILLVAL: 65535
  FORMAT: I5
  LABLAXIS: Qlt Flag
  VALIDMIN: 0
  VALIDMAX: 65535
  VAR_NOTES: >
    Bitwise quality flag {TODO: Store bitwise definition here?}

hi_de_nominal_bin:
  <<: *default_uint8
  CATDESC: Corresponding histogram angle bin for this Direct Event
  FIELDNAM: Histogram Bin Number
  FILLVAL: 511
  FORMAT: I2
  LABLAXIS: Hist Bin \#
  VALIDMIN: 0
  VALIDMAX: 89

# ======= L1C PSET Section =======
hi_pset_epoch:
  <<: *default_epoch

hi_pset_esa_step:
  <<: *default_esa_step
  LABLAXIS: Energy Step
  UNITS: " "
  VALIDMIN: 0
  VALIDMAX: 12
  SCALE_TYP: linear
  MONOTON: INCREASE
  VAR_TYPE: support_data
  dtype: uint8

hi_pset_spin_angle_bin:
  CATDESC: 0.1 degree spin angle bins
  FIELDNAM: Spin angle bin index
  FILLVAL: 65535
  FORMAT: I3
  LABLAXIS: Bin Index
  UNITS: deg
  SCALE_TYP: linear
  MONOTON: INCREASE
  VALIDMIN: 0
  VALIDMAX: 3599
  VAR_TYPE: support_data
  VAR_NOTES: >
    Bins are defined by spin angle about the mean axis of rotation for the pointing set.
    Spin angle bins start at closest to ecliptic North. Bin zero is centered at 0.05 degrees
    spinward of ecliptic North and all bins are 0.1 degrees wide.
  dtype: uint16

# Based on SPDF example of a vector magnetic field variable at the following link,
# despun_z does not need a DEPEND_1 because it does not depend on any support_data
# https://spdf.gsfc.nasa.gov/istp_guide/variables.html#data_eg2
hi_pset_despun_z:
  <<: *default_float32
  CATDESC: Unit vector corresponding to Despun Pointing Frame z-axis in HAE Ecliptic coordinates
  FIELDNAM: Despun Frame z-axis in HAE coordinates
  FORMAT: F5.3
  LABL_PTR_1: label_vector_HAE
  UNITS: " "
  VALIDMIN: -1
  VALIDMAX: 1
  DISPLAY_TYPE: no_plot
  VAR_TYPE: support_data

hi_pset_hae_latitude:
  <<: *default_float32
  CATDESC: Latitude of bin center in HAE coordinates
  FIELDNAM: HAE Latitude
  DEPEND_0: epoch
  DEPEND_1: spin_angle_bin
  DISPLAY_TYPE: no_plot
  FORMAT: F5.2
  LABLAXIS: Latitude
  UNITS: deg
  VALIDMIN: 0
  VALIDMAX: 180

hi_pset_hae_longitude:
  <<: *default_float32
  CATDESC: Longitude of bin center in HAE coordinates
  FIELDNAM: HAE Longitude
  DEPEND_0: epoch
  DEPEND_1: spin_angle_bin
  DISPLAY_TYPE: no_plot
  FORMAT: F5.2
  LABLAXIS: Latitude
  UNITS: deg
  VALIDMIN: 0
  VALIDMAX: 360

hi_pset_counts:
  <<: *default_uint16
  CATDESC: Binned direct events counts during good times
  FIELDNAM: Binned DE counts
  DEPEND_0: epoch
  DEPEND_1: esa_step
  DEPEND_2: spin_angle_bin
  LABL_PTR_1: esa_step_label
  LABL_PTR_2: spin_bin_label
  DISPLAY_TYPE: stack_plot
  FORMAT: I5

hi_pset_exposure_times:
  <<: *default_float32
  CATDESC: Exposure times for each bin during good times
  FIELDNAM: Bin exposure times
  DEPEND_0: epoch
  DEPEND_1: esa_step
  DEPEND_2: spin_angle_bin
  LABL_PTR_1: esa_step_label
  LABL_PTR_2: spin_bin_label
  UNITS: sec
  DISPLAY_TYPE: stack_plot
  FORMAT: F6.2

hi_pset_background_rates:
  <<: *default_float32
  CATDESC: Background count rates
  FIELDNAM: Background count rates
  DEPEND_0: epoch
  DEPEND_1: esa_step
  DEPEND_2: spin_angle_bin
  LABL_PTR_1: esa_step_label
  LABL_PTR_2: spin_bin_label
  UNITS: counts / s
  DISPLAY_TYPE: stack_plot
  FORMAT: F4.2

hi_pset_background_rates_uncertainty:
  <<: *default_float32
  CATDESC: Background count rate uncertainties
  FIELDNAM: Background count rate uncertainties
  DEPEND_0: epoch
  DEPEND_1: esa_step
  DEPEND_2: spin_angle_bin
  LABL_PTR_1: esa_step_label
  LABL_PTR_2: spin_bin_label
  UNITS: counts / s
  DISPLAY_TYPE: stack_plot
  FORMAT: F4.2

# <=== pset label Attributes ===>
hi_pset_spin_bin_label:
  CATDESC: Label spin angle bin
  FIELDNAM: Label spin angle bin
  FORMAT: A4
  VAR_TYPE: metadata

hi_pset_esa_step_label:
  CATDESC: Label esa step
  FIELDNAM: Label esa step
  FORMAT: A4
  VAR_TYPE: metadata

hi_pset_label_vector_HAE:
  CATDESC: Label cartesian despun_z
  FIELDNAM: Label cartesian despun_z
  FORMAT: A5
  VAR_TYPE: metadata